// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tretsykvkjhscgbjukfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZXRzeWt2a2poc2NnYmp1a2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzg4MTgsImV4cCI6MjA1OTg1NDgxOH0.tLofjzkQjO1CZx3glBl3KTp1AdDvvCwpaCeynfRfPrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);